### ISSUE TITLE
devcon failed in windows 8

### ISSUE THREAD

**Issue by hlz2014** [kevinoid/remove-nonpresent-devices#10]
Try to use a file named "installer.cmd" to install driver in windows 8 (x64). The content of the file is " @echo off devcon install ProTouch.inf "HID\ProTouchHidDevice". It has no any error in windows7(x64),but in windows8(x64) "devcon failed" after runing the file.If I open the cmd.exe as an administrator and then input "devcon.exe install ProTouch.inf "HID\ProTouchHidDevice", it will be correct.

**Comment by bellasi** [comment]
i same same problem can one tell me what to do

**Comment by kevinoid** [comment]
I'm a bit confused.  This sounds like a problem with the `installer.cmd` file, or possibly `devcon.exe`.  How is the `removedevices.js` script involved?

**Comment by bellasi** [comment]
please i need to know what to write on cmd.exe
my file is called multikey.inf 
thanks

**Comment by kevinoid** [comment]
I'm sorry, but I have no idea what you are trying to do or how to help you do it.
